import os
import google.generativeai as genai
from typing import Optional
import logging
from datetime import datetime, timedelta

logger = logging.getLogger(__name__)

class GeminiClient:
    def __init__(self, api_key: str, model_name: str = "gemini-1.5-flash"):
        self.api_key = api_key
        self.model_name = model_name
        self.model = None
        self.request_count = 0
        self.last_reset = datetime.now()
        self.max_requests_per_minute = 10

        # Configure Gemini
        genai.configure(api_key=api_key)

        # Initialize the model
        try:
            self.model = genai.GenerativeModel(model_name)
            logger.info(f"Gemini client initialized with model: {model_name}")
        except Exception as e:
            logger.error(f"Failed to initialize Gemini model: {e}")
            raise

    def _check_rate_limit(self) -> bool:
        """Check if we're within rate limits"""
        now = datetime.now()
        if now - self.last_reset > timedelta(minutes=1):
            self.request_count = 0
            self.last_reset = now

        return self.request_count < self.max_requests_per_minute

    def _create_dark_fantasy_prompt(self, user_prompt: str) -> str:
        """Enhance user prompt with dark fantasy context"""
        system_prompt = """You are AYNAGH0R, a master storyteller of dark fantasy tales.
        Your stories are atmospheric, mysterious, and richly detailed.
        You weave narratives that blend gothic horror with medieval fantasy,
        creating immersive worlds filled with ancient magic, shadowy creatures,
        and morally complex characters.

        Style guidelines:
        - Use vivid, atmospheric descriptions
        - Create tension and mystery
        - Include elements of the supernatural
        - Maintain a dark, gothic tone
        - Keep responses engaging and immersive
        - Aim for 200-500 words unless specified otherwise

        User's story request: """

        return f"{system_prompt}\n\n{user_prompt}"

    def generate(self, prompt: str, max_retries: int = 3) -> str:
        """Generate story content using Gemini API"""
        if not self.model:
            return "❌ Gemini model not initialized. Please check your API key."

        if not self._check_rate_limit():
            return "⏱️ Rate limit exceeded. Please wait a moment before generating another story."

        try:
            # Enhance prompt for dark fantasy context
            enhanced_prompt = self._create_dark_fantasy_prompt(prompt)

            # Configure generation parameters
            generation_config = genai.types.GenerationConfig(
                candidate_count=1,
                max_output_tokens=1000,
                temperature=0.8,
                top_p=0.9,
                top_k=40
            )

            # Safety settings for creative content
            safety_settings = [
                {
                    "category": "HARM_CATEGORY_HARASSMENT",
                    "threshold": "BLOCK_MEDIUM_AND_ABOVE"
                },
                {
                    "category": "HARM_CATEGORY_HATE_SPEECH",
                    "threshold": "BLOCK_MEDIUM_AND_ABOVE"
                },
                {
                    "category": "HARM_CATEGORY_SEXUALLY_EXPLICIT",
                    "threshold": "BLOCK_MEDIUM_AND_ABOVE"
                },
                {
                    "category": "HARM_CATEGORY_DANGEROUS_CONTENT",
                    "threshold": "BLOCK_MEDIUM_AND_ABOVE"
                }
            ]

            # Generate content
            response = self.model.generate_content(
                enhanced_prompt,
                generation_config=generation_config,
                safety_settings=safety_settings
            )

            self.request_count += 1

            if response.candidates and response.candidates[0].content:
                story = response.candidates[0].content.parts[0].text

                # Add atmospheric formatting
                formatted_story = f"""🌙 **AYNAGH0R's Tale** 🌙

{story}

*Generated by the dark fantasy AI storyteller*"""

                logger.info(f"Successfully generated story of {len(story)} characters")
                return formatted_story
            else:
                logger.warning("Gemini returned empty response")
                return "🌫️ The mists of inspiration are unclear. Please try a different prompt."

        except Exception as e:
            logger.error(f"Gemini API error: {e}")

            if "quota" in str(e).lower() or "limit" in str(e).lower():
                return "📊 Daily quota exceeded. The storyteller needs rest until tomorrow."
            elif "safety" in str(e).lower():
                return "🛡️ Content filtered for safety. Please try a different story theme."
            else:
                return f"⚠️ Storytelling magic failed: {str(e)[:100]}..."

    def test_connection(self) -> bool:
        """Test if Gemini API is accessible"""
        try:
            test_response = self.generate("Test connection")
            return "Test connection" not in test_response or "error" not in test_response.lower()
        except:
            return False